version: '3'

services:
  packetgen:
    privileged: true
    network_mode: "host"
    image: electrocucaracha/packetgen
    build:
      context: ./packetgen
  firewall:
    privileged: true
    network_mode: "host"
    image: electrocucaracha/firewall
    build:
      context: ./firewall
  sink:
    privileged: true
    network_mode: "host"
    image: electrocucaracha/sink
    build:
      context: ./sink
  darkstat:
    network_mode: "host"
    image: electrocucaracha/darkstat
    build:
      context: ./darkstat
