---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020,2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

version: '3'

services:
  vpp-agent:
    restart: always
    image: ligato/vpp-agent:v3.4.0
    privileged: true
    environment:
      - ETCD_CONFIG=disabled
    volumes:
      - vpp-sock:/run/vpp/
      - pg_streams:/opt/pg_streams/
  packetgen:
    restart: always
    image: packetgen:1.6.0
    build:
      context: ./packetgen
    networks:
      unprotected:
        ipv4_address: 192.168.10.200
    depends_on:
      - vpp-agent
    volumes:
      - vpp-sock:/run/vpp/
      - pg_streams:/opt/pg_streams/
    cap_add:
      - NET_ADMIN
  firewall:
    restart: always
    image: firewall:1.6.0
    build:
      context: ./firewall
    networks:
      unprotected:
        ipv4_address: 192.168.10.100
      protected:
        ipv4_address: 192.168.20.100
    depends_on:
      - vpp-agent
    volumes:
      - vpp-sock:/run/vpp/
    cap_add:
      - NET_ADMIN
  sink:
    restart: always
    image: sink:1.6.0
    cap_add:
      - NET_ADMIN
    ports:
      - 667:667
    build:
      context: ./sink
    networks:
      protected:
        ipv4_address: 192.168.20.250
    depends_on:
      - packetgen

networks:
  unprotected:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  protected:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

volumes:
  vpp-sock:
  pg_streams:
